name: Flask web project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: dhananjaypuri
      IMAGE_NAME: gitaction-flask
      TAG: latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Image Build
        run: |
          echo "${{ github.GITHUB_RUN_ID }}"
          echo ${{ env.DOCKER_REPO }}
      - name: Image Push
        run: echo "Image pushed successfully !!!!!!"
  # deploy_to_server:
  #   runs-on: ubuntu-latest
  #   steps:
