name: Flask web project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI: 
    runs-on: ubuntu-latest
    env:
      DOCKER_UNAME: dhananjaypuri
      DOCKER_REPO: dhananjaypuri
      IMAGE_NAME: gitaction-flask
      TAG: latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Image Build
        run: |
          docker build -t "${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest" .
          
      - name: Image Push
        run: |
          docker images
          echo ${{ secrets.DOCKER_PASSWD }} | docker login -u ${{ env.DOCKER_UNAME }} --password-stdin
          docker image push "${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest"
          
  CD:
    runs-on: ubuntu-latest
    needs: CI
    env:
      HOST_IP: 44.204.45.157
      HOST_USER: ubuntu
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST_IP }}
          password: ${{ secrets.SRV_PASSWD }}
          username: ${{ env.HOST_USER }}
          port: 22
          script: |
            if docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$
            then
              container_id=$(docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$ | awk '{print $1}')
              container_name=$(docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$ | awk '{print $2}')
              echo "Container ID : ${container_id} to be deleted"
            else
              echo "Container already running"
            fi
