name: Flask web project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      DOCKER_UNAME: dhananjaypuri
      DOCKER_REPO: dhananjaypuri
      IMAGE_NAME: gitaction-flask
      TAG: latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Image Build
        run: |
          docker build -t "${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest" .
          
      - name: Image Push
        run: |
          docker images
          echo ${{ secrets.DOCKER_PASSWD }} | docker login -u ${{ env.DOCKER_UNAME }} --password-stdin
  # deploy_to_server:
  #   runs-on: ubuntu-latest
  #   steps:
