name: Flask web project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI: 
    runs-on: ubuntu-latest
    env:
      DOCKER_UNAME: dhananjaypuri
      DOCKER_REPO: dhananjaypuri
      IMAGE_NAME: gitaction-flask
      TAG: latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Image Build
        run: |
          docker build -t "${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest" .
          
      - name: Image Push
        run: |
          docker images
          echo ${{ secrets.DOCKER_PASSWD }} | docker login -u ${{ env.DOCKER_UNAME }} --password-stdin
          docker image push "${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest"
          
  CD:
    runs-on: ubuntu-latest
    needs: CI
    env:
      HOST_IP: 44.204.45.157
      HOST_USER: ubuntu
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST_IP }}
          password: ${{ secrets.SRV_PASSWD }}
          username: ${{ env.HOST_USER }}
          port: 22
          script: |
            if docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$
            then
              echo ${{ secrets.DOCKER_PASSWD }} | docker login -u dhananjaypuri --password-stdin
              container_id=$(docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$ | awk '{print $1}')
              container_name=$(docker ps --format "{{.ID}} {{.Names}}" | grep gitflask$ | awk '{print $2}')
              echo "Container ID : ${container_id} to be deleted"
              docker container kill ${container_id}
              docker container rm -f ${container_name}
              if [[ $? -eq 0 ]]
              then
                echo "Container Deleted Successfully !!!!!"
                docker pull dhananjaypuri/gitpython:latest
                docker container run -d --name gitflask -p 5000:5000 dhananjaypuri/gitpython
                if [[ $? -eq 0 ]]
                then
                  echo "Container Started Successfully !!!!!"
                else
                  echo "Container cannot be started"
                fi
              else
                echo "Container cannot be deleted"
              fi 
            else
              echo "Starting container as it was not running !!!!!!!!"
              docker pull dhananjaypuri/gitpython:latest
              docker container run -d --name gitflask -p 5000:5000 dhananjaypuri/gitpython
              if [[ $? -eq 0 ]]
              then
                echo "Container Started Successfully !!!!!"
              else
                echo "Container cannot be started"
              fi
            fi
